apiVersion: apps/v1
kind: Deployment
metadata:
  name: adetxt-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adetxt-user
  template:
    metadata:
      labels:
        app: adetxt-user
    spec:
      containers:
      - name: adetxt-user-app
        image: adetxt-user
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080