name: publish
on: [push]
jobs:
  publish-adetxt-user-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the adetxt-user Docker image
        run: |
              docker build . --tag ghcr.io/adetxt/user:latest
              docker run ghcr.io/adetxt/user:latest
              docker push ghcr.io/adetxt/user:latest